draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 10  # no effect?
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 10
  outer_pad_h: 30
  line_spacing: 1
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 4
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_style: ""  # <- automatically updated from style.sass
  svg_extra_style: ''
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://cdn.jsdelivr.net/npm/@tabler/icons@2.46.0/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    lucide: https://cdn.jsdelivr.net/npm/lucide-static@0.310.0/icons/{}.svg  # has copyright as first line -> breaks keymap
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
      hold: "reset"  # annotation only
    "&bootloader":
      tap: $$mdi:restore-alert$$
      hold: "boot"  # annotation only

    "&bt BT_SEL 0":
      tap: "BT  0"  # double space to disable linebreak
    "&bt BT_SEL 1":
      tap: "BT  1"
    "&r_bt0_clr":
      tap: "BT0+CLR"
    "&r_bt1_clr":
      tap: "BT1+CLR"

    # (german keys from raw_binding_map.gen.yaml automatically added)
  sticky_label: sticky
  toggle_label: toggle
  trans_legend:
    tap: $$mdi:triangle-down-outline$$  # ▽
    type: trans
  mark_alternate_layer_activators: false
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map: {}
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    LCTRL: 
        tap: $$mdi:apple-keyboard-control$$
        type: rmod
    LALT: 
        tap: $$mdi:apple-keyboard-option$$
        type: rmod
    LSHIFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    LSHFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    LCMD: 
        tap: $$mdi:apple-keyboard-command$$
        type: rmod
    RCTRL: 
        tap: $$mdi:apple-keyboard-control$$
        type: rmod
    RALT: 
        tap: $$mdi:apple-keyboard-option$$
        type: rmod
    RSHIFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    RSHFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    RCMD: 
        tap: $$mdi:apple-keyboard-command$$
        type: rmod

    TAB: $$mdi:keyboard-tab$$
    ESCAPE: $$mdi:keyboard-esc$$
    RETURN: $$mdi:keyboard-return$$
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace-outline$$

    C_BRI_DN: $$tabler:sun-low$$          # see style.scss
    C_BRI_UP: $$tabler:sun-high$$         # see style.scss
    C_PREV: $$tabler:player-track-prev$$  # see style.scss
    C_PP: $$tabler:player-play$$          # see style.scss
    C_NEXT: $$tabler:player-track-next$$  # see style.scss
    C_MUTE: $$tabler:volume-3$$           # see style.scss
    C_VOL_DN: $$tabler:volume-2$$         # see style.scss
    C_VOL_UP: $$tabler:volume$$           # see style.scss

    UP: $$mdi:chevron-up$$
    DOWN: $$mdi:chevron-down$$
    LEFT: $$mdi:chevron-left$$
    RIGHT: $$mdi:chevron-right$$
  zmk_combos: {}
