draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 10  # no effect?
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 10
  outer_pad_h: 30
  line_spacing: 1
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 4
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_style: ""  # <- automatically updated from style.sass
  svg_extra_style: ''
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs:
    r:alt-left: |
      <svg viewBox="0 0 48 24">
        <use href="#mdi:apple-keyboard-option" x="-12" y="0" height="24" width="24"/>
        <use href="#mdi:chevron-left" x="12" y="0" height="24" width="24"/>
      </svg>
    r:alt-right: |
      <svg viewBox="0 0 48 24">
        <use href="#mdi:apple-keyboard-option" x="-12" y="0" height="24" width="24"/>
        <use href="#mdi:chevron-right" x="12" y="0" height="24" width="24"/>
      </svg>
    r:alt-plus: |
      <svg viewBox="0 0 48 24">
        <defs>
          <svg id="rmdi:plus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>plus</title><path d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
        </defs>
        <use href="#mdi:apple-keyboard-option" x="-12" y="0" height="24" width="24"/>
        <use href="#rmdi:plus" x="12" y="0" height="24" width="24"/>
      </svg>
    r:hyper-TEMPLATE: |  # hyper+key for all alpha keys are generated from this config
      <svg viewBox="0 0 48 24">
        <path d="M12,11A1,1 0 0,1 13,12A1,1 0 0,1 12,13A1,1 0 0,1 11,12A1,1 0 0,1 12,11M4.22,4.22C5.65,2.79 8.75,3.43 12,5.56C15.25,3.43 18.35,2.79 19.78,4.22C21.21,5.65 20.57,8.75 18.44,12C20.57,15.25 21.21,18.35 19.78,19.78C18.35,21.21 15.25,20.57 12,18.44C8.75,20.57 5.65,21.21 4.22,19.78C2.79,18.35 3.43,15.25 5.56,12C3.43,8.75 2.79,5.65 4.22,4.22M15.54,8.46C16.15,9.08 16.71,9.71 17.23,10.34C18.61,8.21 19.11,6.38 18.36,5.64C17.62,4.89 15.79,5.39 13.66,6.77C14.29,7.29 14.92,7.85 15.54,8.46M8.46,15.54C7.85,14.92 7.29,14.29 6.77,13.66C5.39,15.79 4.89,17.62 5.64,18.36C6.38,19.11 8.21,18.61 10.34,17.23C9.71,16.71 9.08,16.15 8.46,15.54M5.64,5.64C4.89,6.38 5.39,8.21 6.77,10.34C7.29,9.71 7.85,9.08 8.46,8.46C9.08,7.85 9.71,7.29 10.34,6.77C8.21,5.39 6.38,4.89 5.64,5.64M9.88,14.12C10.58,14.82 11.3,15.46 12,16.03C12.7,15.46 13.42,14.82 14.12,14.12C14.82,13.42 15.46,12.7 16.03,12C15.46,11.3 14.82,10.58 14.12,9.88C13.42,9.18 12.7,8.54 12,7.97C11.3,8.54 10.58,9.18 9.88,9.88C9.18,10.58 8.54,11.3 7.97,12C8.54,12.7 9.18,13.42 9.88,14.12M18.36,18.36C19.11,17.62 18.61,15.79 17.23,13.66C16.71,14.29 16.15,14.92 15.54,15.54C14.92,16.15 14.29,16.71 13.66,17.23C15.79,18.61 17.62,19.11 18.36,18.36Z" />
        <text x="24" y="14" style="font-size: 24px; text-anchor: start;">(CHAR)</text>
      </svg>
  glyph_urls:
    tabler: https://cdn.jsdelivr.net/npm/@tabler/icons@2.46.0/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    lucide: https://cdn.jsdelivr.net/npm/lucide-static@0.310.0/icons/{}.svg  # has copyright as first line -> breaks keymap
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
      hold: "reset"  # annotation only
    "&bootloader":
      tap: $$mdi:restore-alert$$
      hold: "boot"  # annotation only

    "&bt BT_SEL 0":
      tap: "BT  0"  # double space to disable linebreak
    "&bt BT_SEL 1":
      tap: "BT  1"
    "&r_bt0_clr":
      tap: "BT0+CLR"
    "&r_bt1_clr":
      tap: "BT1+CLR"

    "&uni_times":
      tap: "×"
      hold: "U+00D7"
    "&uni_fwast":
      tap: $$tabler:asterisk-simple$$  # "＊"
      hold: "U+FF0A"
    "&uni_square":
      tap: "□²"
      # ☐  U+2610      BALLOT BOX / Miscellaneous Symbols
      # □  U+25A1      WHITE SQUARE / Geometric Shapes <<== this one
      # ▫  U+25AB      WHITE SMALL SQUARE / Geometric Shapes
      hold: "U+00B2"
    "&uni_hun_o":
      tap: "ő"
      hold: "U+0151"
    "&uni_larr":
      tap: "←"
      hold: "U+2190"
    "&uni_rarr":
      tap: "→"
      hold: "U+2192"
    "&mm_uml_circ":
      tap: "¨"
      shifted: "^"
      type: rdead
    
    '&kp DE_ACUTE':
      tap: ´
      shifted: '`'
      type: rdead
    '&kp DE_ACUTE_ACCENT':
      tap: ´
      shifted: '`'
      type: rdead
    # TODO: why do I need both?
    
    '&kp LA(DE_PLUS)':
      tap: $$r:alt-plus$$
    
    "&sthld RSHFT RSHFT":
      tap: $$mdi:apple-keyboard-shift$$
      type: rmod
      hold: sticky
    
    "&kp HYPER(DE_COMMA)":
      tap: $$r:hyper-,$$
    "&kp HYPER(DE_DOT)":
      tap: $$r:hyper-.$$
    "&kp HYPER(DE_MINUS)":
      tap: $$r:hyper--$$


    # (german keys from raw_binding_map.gen.yaml automatically added)
  sticky_label: sticky
  toggle_label: toggle
  trans_legend:
    tap: $$mdi:triangle-down-outline$$  # ▽
    type: trans
  mark_alternate_layer_activators: false
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map: {}
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    LCTRL: 
        tap: $$mdi:apple-keyboard-control$$
        type: rmod
    LALT: 
        tap: $$mdi:apple-keyboard-option$$
        type: rmod
    LSHIFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    LSHFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    LCMD: 
        tap: $$mdi:apple-keyboard-command$$
        type: rmod
    RCTRL: 
        tap: $$mdi:apple-keyboard-control$$
        type: rmod
    RALT: 
        tap: $$mdi:apple-keyboard-option$$
        type: rmod
    RSHIFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    RSHFT: 
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    "&sthld RSHFT":
        tap: $$mdi:apple-keyboard-shift$$
        type: rmod
    RCMD: 
        tap: $$mdi:apple-keyboard-command$$
        type: rmod
    "RA(U)":
        tap: "¨"
        type: rdead

    TAB: $$mdi:keyboard-tab$$
    ESCAPE: $$mdi:keyboard-esc$$
    RETURN: $$mdi:keyboard-return$$
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace-outline$$
    DELETE: $$mdi:backspace-reverse-outline$$

    # PG_UP: ⇞  # resvg: Fallback from Liberation Mono to Arial Unicode MS.
    # PG_DN: ⇟  # resvg: Fallback from Liberation Mono to Arial Unicode MS.
    # HOME: ↖ # $$mdi:arrow-top-left$$
    # HOME: $$mdi:arrow-top-left$$
    # HOME: $$tabler:arrow-up-left$$
    # END: $$mdi:arrow-bottom-right$$
    # END: ↘  # resvg: Fallback from Liberation Mono to SF Pro.

    C_BRI_DN: $$tabler:sun-low$$          # see style.scss
    C_BRI_UP: $$tabler:sun-high$$         # see style.scss
    C_PREV: $$tabler:player-track-prev$$  # see style.scss
    C_PP: $$tabler:player-play$$          # see style.scss
    C_NEXT: $$tabler:player-track-next$$  # see style.scss
    C_MUTE: $$tabler:volume-3$$           # see style.scss
    C_VOL_DN: $$tabler:volume-2$$         # see style.scss
    C_VOL_UP: $$tabler:volume$$           # see style.scss

    UP: $$mdi:chevron-up$$
    DOWN: $$mdi:chevron-down$$
    LEFT: $$mdi:chevron-left$$
    RIGHT: $$mdi:chevron-right$$

    'LA(LEFT)': $$r:alt-left$$
    'LA(RIGHT)': $$r:alt-right$$
    'LA(DE_PLUS)': $$r:alt-plus$$

    C_AL_KEYBOARD_LAYOUT: $$tabler:player-eject$$
  zmk_combos: {}
